name: Continuous Integration

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.0, 8.1]
        dependency-version: [prefer-stable]

    name: CI - PHP ${{ matrix.php }}  - (${{ matrix.dependency-version }})

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, zip
          tools: prestissimo
          coverage: pcov

      - name: Install Composer dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist --no-suggest
      - name: PHPUnit Testing
        run: vendor/bin/phpunit tests